
spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/test
    username: user
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
#        show_sql: true
#        sout -> logging ref
        format_sql: true
        default_batch_fetch_size: 100
#    open-in-view: false

#       logging
logging:
  level:
    org.hibernate.SQL: debug
    #    sql to log able
#    org.hibernate.type: trace
    # paramemter to log


